server:
  port: 14001
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.6.99:3306/gmall_order?userSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    tracer: trace  #打开追踪器
