server:
  port: 10001
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris: http://192.168.6.99:9200
thread:
  param:
    core: 4
    max: 8
    queueSize: 100
    keepAliveTime: 300
logging:
  level:
    tracer: trace  #打开追踪器
    org.elasticsearch: trace