server:
  port: 8000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  zipkin:
    base-url: http://192.168.6.99:9411/
    sender:
      type: web
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

feign:
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 500
  #     retryer: 自定义的包全类名，定义重试几次
