server:
  port: 80
spring:
  profiles:
    active: dev
  zipkin:
    base-url: http://192.168.6.99:9411
    sender:
      type: web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #只要有人处理请求了，这个跨域就能生效
            allowedOrigins: "*" #允许所有地址来源跨域
            allowedMethods: "*"  #允许所有请求方式跨域
            allowedHeaders: "*"  #允许请求头携带的参数
            allowedCredentials: true #允许携带一些安全标志跨域，如cookie
      routes:
        - id: product_route # 以 /admin/product 开头的所有请求都lb(loadbalancer)转给service-product
          uri: lb://service-product
          predicates: #断言
            - Path=/admin/product/**
        - id: user_route
          uri: lb://service-login
          predicates:
            - Path=/api/user/**
        - id: web-all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com
  redis:
    host: 192.168.6.99
    password: gm123456