server:
  port: 9001
spring:
  zipkin:
    base-url: http://192.168.6.99:9411/
    sender:
      type: web
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration