server:
  port: 9001
spring:
  zipkin:
    base-url: http://192.168.6.99:9411/
    sender:
      type: web
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  redis:
    port: 6379
    host: 192.168.6.99
    password: gm123456
thread:
  param:
    core: 4
    max: 8
    queueSize: 100
    keepAliveTime: 300